version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mnist_mongodb
    restart: always
    ports:
      - "27018:27017"  # Host:Container
    environment:
      MONGO_INITDB_DATABASE: mnist_db
    volumes:
      - mongodb_data:/data/db

  fastapi_app:
    build: .
    container_name: mnist_fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      # Override MONGO_URI to use Docker internal network
      MONGO_URI: mongodb://mongodb:27017/
      MONGO_DB_NAME: mnist_db
      RUNNING_IN_DOCKER: "true"
    volumes:
      - .:/app

volumes:
  mongodb_data:
