version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mnist_mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db

  fastapi_app:
    build: .
    container_name: mnist_fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}  # This will be replaced by Docker
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      RUNNING_IN_DOCKER: "true"  # Flag to indicate Docker environment
    volumes:
      - .:/app

volumes:
  mongodb_data:
