name: Run Pytest

on:
  workflow_run:
    workflows: ["Upload Model"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Restore pretrained model from cache
      id: cache-model
      uses: actions/cache@v4
      with:
        path: src/models/model.pkl
        key: pretrained-model-v1

    - name: Download pretrained model artifact if cache miss
      if: steps.cache-model.outputs.cache-hit != 'true'
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: src/models

    - name: Check if model file exists
      id: check_model
      run: |
        if [ -f "src/models/model.pkl" ]; then
          echo "model_exists=true" >> $GITHUB_OUTPUT
        else
          echo "❌ Model file not found!"
          echo "model_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Start MongoDB
      if: steps.check_model.outputs.model_exists == 'true'
      uses: supercharge/mongodb-github-action@1.12.0
      with: 
        mongodb-version: '6.0.5'

    - name: Run tests
      if: steps.check_model.outputs.model_exists == 'true'
      env: 
        MONGODB_URI: mongodb://localhost:27017
      run: pytest

    - name: Fail if model is missing
      if: steps.check_model.outputs.model_exists != 'true'
      run: |
        echo "⚠️ model.pkl not found after checking both cache and artifacts."
        exit 1
