name: Upload Model

on:
  push:
    branches: [main, development]

jobs:
  upload-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload model.pkl artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: src/models/model.pkl
          retention-days: 7

